/**
 * 各模块输出字段 → 中文标签（仅用于展示，无匹配时保留原键名）。
 * 覆盖结果卡片顶层字段与嵌套指标（metrics / intrinsic_value / methods / params / dimensions 等）。
 */
export const FIELD_LABELS: Record<string, string> = {
  // M1 商业模式
  business_type: "生意类型",
  one_liner: "一句话描述",
  understandability: "可理解性",
  industry: "行业",
  // M2 财务质量
  metrics: "核心指标",
  signals: "信号",
  summary: "摘要",
  years: "年报期数",
  roe_latest: "ROE 最新",
  roe_mean: "ROE 均值",
  net_margin: "净利率",
  grossprofit_margin: "毛利率",
  equity_multiplier: "权益乘数",
  implied_asset_turnover: "隐含周转",
  ocf_to_np_min: "近N年最低 现金流/净利比",
  ocfps_eps_min: "近N年最低 每股现金流/利润比",
  debt_to_assets_latest: "资产负债率",
  // M3 成长
  growth_estimate: "增速估计",
  prosperity: "景气度",
  // M4 估值
  methods: "估值方法",
  intrinsic_value: "内在价值区间",
  current_price: "现价",
  params: "估值参数",
  note: "备注",
  low: "低",
  mid: "中",
  high: "高",
  value: "估值",
  growth_rate: "增长率",
  discount_rate: "折现率",
  terminal_growth: "永续增速",
  risk_free_rate: "无风险利率",
  dcf: "DCF 现金流折现",
  tang: "唐朝法",
  graham_number: "格雷厄姆数",
  graham_formula: "格雷厄姆公式",
  ddm: "股利贴现",
  relative_median_pe: "相对中位 PE",
  peg: "PEG（增速匹配PE）",
  pb_band: "PB 估值法",
  pb_roe: "PB-ROE 估值",
  dcf_three_stage: "三阶段 DCF",
  nav: "净资产法（NAV）",
  ncav: "净流动资产法（NCAV）",
  // M4 估值参数（methods.params，规则层产出）
  g: "增速 g",
  r: "折现率 r",
  terminal_g: "永续增速",
  fair_pe: "合理 PE",
  pe_cap: "PE 上限",
  eps3: "3 年 EPS",
  buy: "买入价",
  sell: "卖出价",
  bvps: "每股净资产",
  g_pct: "增速 %",
  y_pct: "股息率 %",
  div: "每股股息",
  spread: "折现利差 (r−g)",
  roe: "ROE",
  implied_pb: "隐含 PB",
  high_years: "高速增长年数",
  decel_years: "减速年数",
  decel_g: "减速期增速",
  profit_base: "利润口径",
  cash_eps: "每股现金流",
  eps: "EPS",
  growth_confidence: "增长信心",
  // M3 增速情景（handoff.growth_scenarios）
  conservative: "保守",
  neutral: "中性",
  optimistic: "乐观",
  financial_subtype: "金融细类",
  valuation_confidence: "估值置信度",
  quality_multiplier: "质量乘数",
  risk_multiplier: "风险折扣",
  total_multiplier: "综合乘数",
  quality_tier: "质量档位",
  quality_score: "质量分",
  kill_switches: "风险开关",
  method_agreement: "方法一致性",
  weights: "方法权重",
  std: "离散度",
  methods_used: "已用方法",
  // M4 LLM 行业校准
  calibration: "行业校准",
  parameter_adjustments: "参数校准",
  method_weight_adjustments: "方法权重校准",
  valuation_confidence_delta: "置信度增量",
  industry_notes: "行业判断",
  risk_notes: "行业风险",
  calibrated_intrinsic: "校准后内在价值",
  // M5 护城河（两层制：规则代理评级 + LLM 定性）
  width: "护城河宽度（最终合成）",
  width_source: "宽度来源",
  width_conflict: "宽度冲突",
  rule_proxy: "规则层（财务代理评级）",
  tier: "代理档位",
  sources: "来源信号",
  source: "来源",
  basis: "依据",
  strength: "强度",
  peer: "同行对比",
  benchmark: "基准类型",
  label: "基准",
  roe_company: "公司 ROE",
  roe_median: "行业中位 ROE",
  margin_key: "利润率口径",
  margin_company: "公司利润率",
  margin_median: "行业中位利润率",
  debt_company: "公司杠杆",
  debt_median: "行业中位杠杆",
  erosion_signals: "规则层侵蚀信号",
  cycle_notes: "周期属性备注",
  debt_note: "杠杆口径说明",
  competition_evidence: "竞争优势证据",
  durability: "持久性",
  trend: "趋势",
  // M6 治理
  dividend_years: "连续分红年数",
  payout_latest: "每股派息",
  dividend_yield: "股息率",
  // M7 市场
  pe_percentile: "PE 分位",
  pb_percentile: "PB 分位",
  position: "估值位置",
  sentiment_heat: "情绪热度",
  sentiment_signals: "情绪信号",
  // M8 安全边际
  price: "现价",
  discount: "折扣率",
  required_discount: "要求折扣",
  buy_price: "买入价",
  sell_price: "卖出价",
  status: "状态",
  // M9 风险
  schema_version: "契约版本",
  module_type: "模块类型",
  core_facts: "核心事实",
  qualitative: "定性分析",
  meta: "质量元数据",
  reason_codes: "降级原因",
  risk_items: "风险清单",
  veto: "否决项",
  // M10 决策
  dimensions: "五维评分",
  total: "加权总分",
  conclusion: "结论",
  vetoed: "否决项",
  // M11 监控
  monitor_rules: "监控规则",
  rule_count: "规则数",
  trigger: "触发条件",
  description: "说明",
  severity: "级别",
  // 五维评分
  business_moat: "护城河",
  financial_quality: "财务质量",
  growth_prosperity: "成长景气",
  valuation_margin: "估值边际",
  governance_risk: "治理风险",
  // LLM 定性
  llm_qualitative: "LLM 定性分析",
  llm_red_team: "LLM 红队批判",
  llm_explanation: "LLM 解释",
  // LLM 结构化字段
  business_model: "商业模式",
  reasons: "判断理由",
  moat_sources: "护城河来源",
  erosion_risks: "侵蚀风险",
  evidence: "证据链",
  governance_assessment: "治理评估",
  capital_allocation: "资本配置",
  risks: "主要风险点",
  key_assumptions: "关键假设",
  permanent_loss_paths: "永久损失路径",
  verdict: "反方结论",
  references: "参考文章",
  // M6 治理（2026-08-07 契约字段）
  governance_score: "治理评分",
  governance_risk_codes: "治理风险码",
  governance_risks: "治理风险",
  capital_allocation_flag: "资本配置档位",
  shareholder_alignment: "股东利益一致性",
  shareholder_alignment_grade: "股东一致性档位",
  disclosure_quality: "信息披露质量",
  disclosure_quality_grade: "披露质量档位",
  // M8 安全边际
  mos_state: "安全边际状态",
  buy_tranches: "分批建仓档位",
  sell_reference: "卖出参考",
  // M9 风险
  vetoes: "一票否决",
  veto_flags: "否决标记",
  max_severity: "最大严重度",
  max_loss_scenario: "压力情景",
  monitor_candidates: "监控候选",
  expected_loss: "期望损失",
  estimated_downside_pct: "估算最大回撤",
  estimated_downside_amount: "回撤金额",
  suggested_position_cap: "建议仓位上限",
  // M10 决策
  decision_code: "决策码",
  blocked_by_veto: "被否决",
  decision_reasons: "决策理由",
  // M11 监控
  message: "说明",
  rule_type: "规则类型",
  action: "动作",
  source_module: "来源模块",
};

export function fieldLabel(key: string): string {
  return FIELD_LABELS[key] ?? key;
}
